#! /usr/bin/env bash

lb config noauto \
    -b iso-hybrid \
    --image-name auto \
    -d jessie \
    --parent-distribution jessie \
    --backports true \
    --debootstrap-options "--variant=minbase --include=busybox-syslogd" \
    --initsystem sysvinit
